[package]
name = "tyr"
version = "0.1.0"
authors = ["Stem Guild <code@stemguild.org>"]
edition = "2021"

[dependencies]
dotenv = "0.15.0"
poise = "0.6.1"
tokio = { version = "1.36.0", features=["rt-multi-thread"] }
env_logger = "0.11.2"
